@startuml
class android.scheduler.johnsalazar.UI.StudentList {
- Repository repository
- RecyclerView studentRecycler
- FloatingActionButton studentListFAB
- StudentAdapter studentAdapter
# void onCreate(Bundle)
# void onResume()
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
}




androidx.appcompat.app.AppCompatActivity <|-- android.scheduler.johnsalazar.UI.StudentList
@enduml